server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: analysis-service
  data:
    mongodb:
      auto-index-creation: true
  autoconfigure:
    exclude: []

<<<<<<< HEAD
=======
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
>>>>>>> 14f19b069fe1f892bbbd7d93fcb4ffa910548193

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  health:
    mongodb:
      enabled: false
