apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: jiaa-backend
type: Opaque
stringData:
  # Docker로 PostgreSQL 실행 시 사용
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/jiwon"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: jiaa-backend
type: Opaque
stringData:
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: jiaa-backend
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<YOUR_AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_AWS_SECRET_ACCESS_KEY>"
  AWS_REGION: "ap-northeast-2"

