server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
<<<<<<< HEAD
      routes:
        # Auth Service
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        
        # User Service
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        
        # Goal Service
        - id: goal-service
          uri: http://goal-service:8080
          predicates:
            - Path=/goal-service/**
          filters:
            - StripPrefix=1
        
        # Analysis Service
        - id: analysis-service
          uri: http://analysis-service:8080
          predicates:
            - Path=/analysis-service/**
          filters:
            - StripPrefix=1
=======
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
>>>>>>> 14f19b069fe1f892bbbd7d93fcb4ffa910548193

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: goal-service
        url: /goal-service/v3/api-docs
      - name: analysis-service
        url: /analysis-service/v3/api-docs
<<<<<<< HEAD
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
=======
    # Swagger UI에서 사용할 서버 URL (localhost로 고정)
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  # 모든 서비스의 서버 URL을 localhost로 오버라이드
  override-with-generic-response: false
  use-management-port: false
>>>>>>> 14f19b069fe1f892bbbd7d93fcb4ffa910548193
